# Uncomment the line below to give your comic page a specific title, otherwise comic_git will use the name of the image file
Title = Last Straw
Post date = 2026-08-12
# You can delete any of the lines below if you don't want to use them.
Alt text = Sassy has had a long and frustrating day. Leave her alone!
Storyline = Changeling Wedding
Characters = Sassy, Mother, Kayra, Singing Cricket, Nanny Muk, Granny Dismal, Tamilda, Maki
#Tags = Tag 1, Tag 2, Tag 3