# Uncomment the line below to give your comic page a specific title, otherwise comic_git will use the name of the image file
Title = Dressed to Impress
Post date = 2026-03-04
# You can delete any of the lines below if you don't want to use them.
Alt text = A version of this magic garment was owned by one of my first D&D characters. 
Storyline = Changeling Wedding
Characters = Tamilda, Kayra, Nanny Muk
#Tags = Tag 1, Tag 2, Tag 3